print("God Academy")
print("God\nAcademy")
print("God\\Academy")
print("God\"Academy")
phrase = "Git Academy"
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.islower())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index(" "))
print(phrase.index("Aca"))
print(phrase.replace("Git" ,"God"))